// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddChatLog(arg1) {
  return window['go']['main']['App']['AddChatLog'](arg1);
}

export function AddLogMsg(arg1) {
  return window['go']['main']['App']['AddLogMsg'](arg1);
}

export function GetCurrentVersion() {
  return window['go']['main']['App']['GetCurrentVersion']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ShowCommands() {
  return window['go']['main']['App']['ShowCommands']();
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
