// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddChatLog(arg1:string):Promise<void>;

export function AddLogMsg(arg1:string):Promise<void>;

export function ClearTradeItems():Promise<void>;

export function GetCatalogItemValue(arg1:string):Promise<number|boolean>;

export function GetCurrentTradeItems():Promise<Array<main.TradeItem>>;

export function GetCurrentVersion():Promise<string>;

export function GetLastTradePartnerName():Promise<string>;

export function GetTradeItemsJSON():Promise<string>;

export function LoadCatalog():Promise<Array<main.CatalogItem>>;

export function LoadConfig():Promise<main.PokerDisplayConfig>;

export function OpenLastTrade():Promise<void>;

export function SaveCatalog(arg1:Array<main.CatalogItem>):Promise<void>;

export function SaveConfig(arg1:main.PokerDisplayConfig):Promise<void>;

export function ShowCommands():Promise<void>;

export function ShowWindow():Promise<void>;

export function SkipDiceSetupForTesting():Promise<void>;
